### ISSUE TITLE
qna/famili100.txt needed but not included

### ISSUE THREAD

**Issue by WillyRL** [azamuddin/kisanak100#1]
as i'm trying to run the fam100 bot, i got error that qna/famili100.txt file is not found
and i found that the file is listed in gitignore 

`I] 2019-12-08T16:05:57Z main.go:110: Fam100 STARTED version= buildtime=
[I] 2019-12-08T16:05:57Z main.go:111: Params quorum=3
[I] 2019-12-08T16:05:57Z main.go:130: loading question DB path=qna/famili100.txt
[F] 2019-12-08T16:05:57Z main.go:134: Failed loading question DB path=qna/famili100.txt error=failed to open "qna/famili100.txt": open qna/famili100.txt: no such file or directory stacktrace=goroutine 1 [running]:
github.com/uber-go/zap.takeStacktrace(0xc00009d800, 0x400, 0x400, 0x0, 0x27, 0xc00002fb90)
	/root/go-root/pkg/mod/github.com/uber-go/zap@v0.0.0-20161123233923-11e8d8f6b3c9/stacktrace.go:33 +0x64
github.com/uber-go/zap.Stack(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go-root/pkg/mod/github.com/uber-go/zap@v0.0.0-20161123233923-11e8d8f6b3c9/field.go:155 +0xa9
github.com/uber-go/zap.AddStacks.func1(0xc000063bc0, 0x0, 0x0)
	/root/go-root/pkg/mod/github.com/uber-go/zap@v0.0.0-20161123233923-11e8d8f6b3c9/hook.go:89 +0x67
github.com/uber-go/zap.(*logger).log(0xc0001cc480, 0x4, 0x917e9c, 0x1a, 0xc00012e500, 0x2, 0x2)
	/root/go-root/pkg/mod/github.com/uber-go/zap@v0.0.0-20161123233923-11e8d8f6b3c9/logger.go:136 +0x1a2
github.com/uber-go/zap.(*logger).Fatal(0xc0001cc480, 0x917e9c, 0x1a, 0xc00012e500, 0x2, 0x2)
	/root/go-root/pkg/mod/github.com/uber-go/zap@v0.0.0-20161123233923-11e8d8f6b3c9/logger.go:114 +0x65
main.main()
	/root/go-root/fam100/cmd/telegram/main.go:134 +0x1167`

**Comment by alikuddah** [comment]
did you manage to solve this?
